### ISSUE TITLE
Where is the code combined bundle adjustment with points and lines?

### ISSUE THREAD

**Issue by qiuyuanWang** [manhofer/Line3Dpp#12]
In your paper, you proposed an algorithm combined bundle adjustment in section 3.5. And I read the whole projection, but I can't find the code. So, would you like to tell me where is the code ?

Thanks

**Comment by manhofer** [comment]
The fully combined bundle adjustment which also affects the 3D point
coordinates and the camera poses is not implemented in this code. It was
implemented as standalone app in the TU Graz SfM pipeline during my time as
research assistant there. For this open source implementation it would have
been too time consuming to allow bundling for all these different SfM
inputs. Sorry to disappoint you here!

Best,
Manuel

**Comment by qiuyuanWang** [comment]
OK, I see. Thanks !
