### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by Lightolx** [manhofer/Line3Dpp#13]
when I change the cmake_build_type from release to debug, errors like "libline3Dpp.so: undefined reference to `ceres::Problem::SetParameterBlockConstant(double*)" appear, how can I solve this?

**Comment by manhofer** [comment]
How did you install CERES? Did you only build it in release, or in debug mode as well?

**Comment by Lightolx** [comment]
Awesome! Since I reinstall ceres in debug mode, no errors appear again, thank you for your reminding
