### ISSUE TITLE
The SfM pipeline output issue: the output of COLMAP and PIX4D doesn't match with LINE3D++ input

### ISSUE THREAD

**Issue by Hufangqiao** [manhofer/Line3Dpp#14]
The output file name of COLMAP 3.3 ends up with <.bin>, while you take <.txt> as input. I want to know your COLMAP version, thanks very much!

**Comment by Hufangqiao** [comment]
The output file name of COLMAP 3.3 ends up with <.bin>, while you take <.txt> as input. I want to know your COLMAP version, thanks very much!

**Comment by manhofer** [comment]
The colmap version I was using when I implemented Lined3D++ was one from early 2016 (I don't remember exactly which one...). Is there a way to change the colmap output format back to .txt somewhere in the options?

**Comment by Hufangqiao** [comment]
Thx, I'll check the early 2016 COLMAP version!

**Comment by Hufangqiao** [comment]
Here I find a solution.

> To convert between the binary and text format in the GUI, you can load the model using ``File > Import model`` and then export the model in the desired output format using ``File > Export model`` (binary) or ``File > Export model as text`` (text). In addition, you can export sparse models to other formats, such as VisualSfM's NVM, Bundler files, PLY, VRML, etc., using ``File > Export as...``. To convert between various formats from the CLI, use the ``model_converter`` executable.

**Comment by manhofer** [comment]
Great!
