### ISSUE TITLE
Where is the cuda.h

### ISSUE THREAD

**Issue by libaosuan** [manhofer/Line3Dpp#15]
When I run the main_vsfm.cpp,an error(fatal error: cuda.h: No such file or directory) occurs.How to deal with it?

**Comment by manhofer** [comment]
Do you have cuda installed? It is a library/toolbox from Nvidia, and
requires an Nvidia graphics card.
If you don't have it, just disable cuda in the Line3D++ CmakeLists.txt.
Then it should build fine.

Best,
Manuel

libaosuan <notifications@github.com> schrieb am Mi., 7. März 2018, 05:56:

**Comment by libaosuan** [comment]
I have cuda.But I don't know where is the header.

**Comment by manhofer** [comment]
If cuda is properly installed, the header should automatically be found. It
is none of my own files.
Try searching for it on the command line. Are you using Windows or Linux?
If Linux, it should be somewhere in /usr/local or /usr/local/lib I think.

Best,

Manuel

libaosuan <notifications@github.com> schrieb am Mi., 7. März 2018, 06:24:

**Comment by libaosuan** [comment]
Thanks @manhofer ,I have found the header.If I should copy the header from the /usr/local/cuda-8.0 to the Line3D++.
