### ISSUE TITLE
How to display the 3d-line model?

### ISSUE THREAD

**Issue by qco-11** [manhofer/Line3Dpp#24]
hello,
thank you for sharing such a nice code in advance, and it's working well in my computer

but when I got my output files such as .obj file and.txt file
I don't know how to connect points(start-points,end-points) into line segments and visualize these(3d-lines) like pictures in your paper.
Looking forward to your reply.

**Comment by manhofer** [comment]
Hi

To visualize the results you can for example use [CloudCompare](https://www.danielgm.net/cc/) to view the .obj files, or [Meshlab](https://www.meshlab.net/) to view they .stl files. Be aware that when you open the .stl in Meshlab you have to untick the option "Unify Duplicated Vertices" and press OK. Then switch to "Wireframe", "Hidden Lines" or "Flat Lines" mode and you should see a result.

The .txt files cannot be visualized directly. This is just an internal human readable format.

Best,
Manuel

**Comment by qco-11** [comment]
Hi Manuel, thank you very much for your help.
I obtained the 3d-line model successfully.
