### ISSUE TITLE
could not find CeresConfig 

### ISSUE THREAD

**Issue by chaiein** [manhofer/Line3Dpp#7]
![image](https://cloud.githubusercontent.com/assets/6629189/23309586/9cff2e1e-faf2-11e6-91e9-ab23a68d79a7.png)

Though the cere-solver is successful stil I am not able to solve the above issue. Please help me to solve this problem

**Comment by manhofer** [comment]
Do you have ceres installed? With "sudo make install"?
Can you find the findceres.cmake file anywhere on your disk?

Best,
Manuel


Am 24.02.2017 16:39 schrieb "chaiein" <notifications@github.com>:

**Comment by chaiein** [comment]
https://github.com/ceres-solver/ceres-solver 
I used the above link. And Findcere.cmake not found

**Comment by chaiein** [comment]
![image](https://cloud.githubusercontent.com/assets/6629189/23310263/5212979e-faf5-11e6-923a-38e6ca1d44e5.png)
 I found the new error after sudo make install

**Comment by chaiein** [comment]
Hi @manhofer 
Thank you for your quick response
I Solved this by setting path for glflag_DIR to its build location.
