### ISSUE TITLE
Can vsfm_result.nvm file be replaced with realtime data?

### ISSUE THREAD

**Issue by chaiein** [manhofer/Line3Dpp#9]
How is the vsfm_result.nvm file is created? What is neccessary changes needed to make use of data online?

**Comment by manhofer** [comment]
this file is created as an output of the VisualSfM pipeline: http://ccwu.me/vsfm/

Line3D++ is not online capable as it is. However, it is not too complicated to make it real-time capable. Have a look at my Dissertation (Chapter 5):
https://www.researchgate.net/publication/305402858_Building_with_Lines_Efficient_3D_Scene_Abstraction_for_the_Built_Environment?ev=prf_pub

**Comment by chaiein** [comment]
Hi @manhofer  I am not able to download your Dissertation. Download fails after few minutes. I tried several times but it fails.

**Comment by manhofer** [comment]
this should work: http://www.icg.tugraz.at/Members/hofer7/building-with-lines-efficient-3d-scene-abstraction-for-the-built-environment/at_download/file

**Comment by chaiein** [comment]
@manhofer  Thank you so much I got it:)
